10.26 수업과제
team-jigun/JavaScript-Class pull request #15
Opened 2022-10-30 05:06 UTC by yvsc5020

수업과제 제출합니다

2022-11-01 14:15 UTC, fred16157 commented on Task/first.js
> +printer("test");
printer 메소드가 없어서 에러가 날 것 같군요
메소드 이름이 변경된 경우 사용하는 곳에서도 바꿔주시길 바랍니다

2022-11-02 00:15 UTC, dokdogalmaegi requested changes

2022-11-02 00:15 UTC, dokdogalmaegi commented on Task/first.js
> +  for (let i of arguments) {
arguments 보다는 rest 문법을 사용해주세요

2022-11-03 12:14 UTC, dokdogalmaegi approved these changes
리뷰 완료

2022-11-08 09:37 UTC, yvsc5020 reviewed
과제 제출

2022-11-08 09:38 UTC, yvsc5020 reviewed
과제 제출

2022-11-08 10:11 UTC, merged