과제제출
team-jigun/JavaScript-Class pull request #17
Opened 2022-10-31 11:20 UTC by hammi1015

2022-11-01 23:45 UTC, dokdogalmaegi commented
Clock 과제가 없습니다.
과제 3개 모두 제출해주세요

2022-11-02 12:53 UTC, hammi1015 commented
다시 고쳐서 제출 했습니다.

2022-11-03 12:20 UTC, dokdogalmaegi requested changes
2차 리뷰, 수정 해주세요

2022-11-03 12:20 UTC, dokdogalmaegi commented on Task/first.js
> +  for (let i of arguments) {
arguments 사용을 지양하도록 하고, rest 문법을 사용해주세요
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/arguments

2022-11-03 12:20 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +  console.log(j);
디버깅 코드 없애주세요

2022-11-03 12:20 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +let j = 0;
의미 없는 변수명 쓰지 마세요, 
selected, selectedByUser 이런 식으로 변경하는 것이 더 좋을 것 같습니다.

2022-11-03 12:20 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +let den = 0; // Drag Enter Num
약어를 사용하는 변수명이라면, 소문자보다는 대문자로 사용하는 것이 보다 가독성이 좋아보입니다.
이 내용은 선택으로 남겨놓겠습니다.

2022-11-03 12:20 UTC, dokdogalmaegi commented on Clock/Clock.js
> +  clock.innerText = `${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`;
한 자리 시간일 때 01로 표시 되어야 합니다. 
Ex) 1, 2, 3, 4

화면에 나와야 하는 시간 Format은 HH:MM:SS 입니다.
수정해주세요

2022-11-03 12:21 UTC, dokdogalmaegi commented on Task/first.js
> +  for (let i of arguments) {
여기는 꼭 수정 부탁드립니다.

2022-11-04 12:04 UTC, dokdogalmaegi requested changes
Clock 쪽만 수정해주시면, Approved 드리겠습니다.

2022-11-04 12:04 UTC, dokdogalmaegi commented on Clock/Clock.js
> +  clock.innerText = `${hour < 10 ? `0${hour}` : hour}:${
계산식은 변수 할당에서 해결해주세요
어떤 문자열이 출력될지 잘 보이지 않습니다.

innerText에 들어가는 문자열은 `${hour]:${minute}:${second}` 로 명확히 보이도록 해주세요.

2022-11-06 14:43 UTC, dokdogalmaegi approved these changes
리뷰 완료하였습니다.
추가 리뷰는 선택사항입니다.

2022-11-06 14:43 UTC, dokdogalmaegi commented on Clock/Clock.js
> +function check(clock) {
함수를 따로 분리한 의도는 잘 보이는 좋은 시도였습니다.
그러나, 함수 이름이 아쉽네요
무엇을 체크하는지를 이름에 좀 더 추가했으면 너무 좋은 코드가 되었을 것 같습니다.
해당 수정은 선택으로 남기겠습니다.

2022-11-08 10:20 UTC, merged