과제 제출
team-jigun/JavaScript-Class pull request #18
Opened 2022-11-01 11:32 UTC by youngjoon568

막차 탑승!

2022-11-01 13:50 UTC, fred16157 approved these changes
몇몇 개선이 가능할 것 같은 부분에 코멘트를 남겨두었습니다
제가 코멘트로 적어둔 부분은 수정하셔도 좋고 그대로 두셔도 좋습니다

2022-11-01 13:50 UTC, fred16157 commented on Clock/Clock.js
> +
24시간 형식이 아닌 12시간 오전/오후로 나뉘는 형식으로 표시하기 위해 이렇게 하신 것 같군요.
그렇다면 시간 표시 뒤에 AM/PM 또는 오전/오후 등 표시를 해주면 좀 더 좋을 것 같습니다.

2022-11-01 13:50 UTC, fred16157 commented on Clock/Clock.js
> +    $title.innerText = `${hours < 10 ? `0${hours}` : hours}:${minutes < 10 ? `0${minutes}` : minutes}:${seconds < 10 ? `0${seconds}` : seconds}`;
padStart를 쓰시면 10의 자리가 비었을 때 0으로 채우는 걸 간단하게 만들 수 있습니다.
제로필이라고도 부르는 사람도 있고, 보통은 String padding이라고 많이 불러요

예를 들어 hours의 값이 5일 때, hours.padStart(2, '0')을 하시면 "05" 가 나오게 할 수 있습니다. hours의 값이 11일 때는 11 그대로 출력되고요 (10의 자리가 비어있지 않으니 0으로 채워지지 않습니다)

2022-11-01 13:50 UTC, fred16157 commented on RockScissorsPaper/RockScissorsPaper.js
> +};
게임을 진행할 때마다 컴퓨터의 패가 바위 -> 가위 -> 보자기 순으로 로테이션이 도는 것 같은데, 랜덤을 적용하면 유저가 예측하기 어렵게 만들 수 있을 것 같습니다

가위바위보라는 게임은 상대가 낼 패를 모르는 상태에서 진행하는 게 기본적이니까요

2022-11-01 13:50 UTC, fred16157 commented on RockScissorsPaper/RockScissorsPaper.js
> +    } else if ((user == bot) || (user == "scissors" && bot == "scissors") || (user == "paper" && bot == "paper")) {
음 이거는 진짜 몰라서 물어보는 건데(구현하시면서 문제가 있었을 수 있으니), 무승부 조건은 user == bot 조건으로도 충분하지 않나요?

그리고 조건식은 되도록이면 === 을 써서 type이 같음을 보장해주는 것이 좋습니다

2022-11-01 13:55 UTC, fred16157 commented
아 그리고 다음부터는 base 브랜치를 main으로 잡지 마시고 닉네임이랑 같은 브랜치(youngjoon568)로 잡아주세요

2022-11-01 13:56 UTC, youngjoon568 commented on RockScissorsPaper/RockScissorsPaper.js
> +    } else if ((user == bot) || (user == "scissors" && bot == "scissors") || (user == "paper" && bot == "paper")) {
저도 충분하지 않을까 해서 일단 바위만 바꿨습니다. 제가 오류를 찾을 때 이 문제가 있는 줄 알고 고치다가 다른 오류가 생각이 나서 다른 오류를 고치다가 다시 이걸 미처 보지 못 했습니다

2022-11-01 14:03 UTC, fred16157 requested changes

2022-11-01 14:03 UTC, fred16157 commented on Task/first.js
> +console.log(printer('test'));
아; 제가 놓친 부분이 있었네요..
이 부분은 printer 함수가 **message 매개변수를 받지 말아야 합니다**.
```
// 2-1. message는 매개 변수를 받은 만큼 *로 감싼 문자가 출력되어야 한다.
// 2-2. 매개 변수는 배열로 받지 않는다.
```
요것만 수정해서 올려주시면 제가 다시 채점해드릴게요.

2022-11-01 16:17 UTC, dokdogalmaegi requested changes
1차 리뷰, 수정 후 다시 Push 해주세요

2022-11-01 16:17 UTC, dokdogalmaegi commented on Clock/Clock.js
> +const $ = e => document.querySelector(e);
현재 업계에서 보통 Jquery는 사용하지 않고, 오히려 걷어내는 추세입니다.
떄문에, 코드상에서 Jquery 문법을 사용해야만 했던 근거가 없다면 굳이 함수 이름을 $로 하여 Jquery 문법과 같이 사용하는 코드 스타일 지양하는게 좋을 것 같습니다.

만약, Jquery문법과 같이 사용하려 한 것이 아닌 또 다른 명확한 근거가 있는 $ 이름의 함수라면 이유를 작성해주세요.

2022-11-01 16:17 UTC, dokdogalmaegi commented on Clock/Clock.js
> +const textPad = str => String(str).padStart(2, "0");
textPad라는 함수는 불필요한 함수입니다.
왜냐하면, 현재 textPad의 역할은 매개 변수로 받은 str 값을 String으로 변환 후 String 내장 함수인 padStart를 쓰는 것이 전부입니다.
여기서 String으로 변환하는 것은 사용 부분을 봤을 때 크게 메리트가 없어 보이며(만약 String 외 값을 매개 변수로 받지 않기 위함이라면, 따로 에러를 뱉거나 type 체크 부분이 들어가 있어야 보다 필요한 함수가 됩니다.), Time 관련 로직을 함수로 만들고 싶은거라면 Time이라는 Custom Class를 만들어 내부 메소드를 구현하는 것이 좋을 것 같습니다.
위 내용이 잘 이해가 되지 않는다면, 내일 수업 시간에 다시 리뷰를 통해 알려드리도록 하겠습니다.

2022-11-01 16:17 UTC, dokdogalmaegi commented on Clock/Clock.js
> +    let text = "";
text라는 변수명은 해당 변수가 나타내는 내용을 정확히 표현하지 못하는 변수명입니다.
meridiemText와 같은 보다 명확한 변수명이 좀 더 코드의 가독성을 높일 수 있지 않을까요?

2022-11-01 16:17 UTC, dokdogalmaegi commented on Clock/Clock.js
> +        if(text === "AM" && hours === 0) {
위 text = "AM"으로 인해 이미 text가 "AM"으로 할당되어 있는 상태에서 text === "AM" 이라는 조건이 필요한 이유가 있나요?
없다면, 지워주세요

2022-11-01 16:17 UTC, dokdogalmaegi commented on Clock/Clock.js
> +    setTimeout(() => {
setTImeout을 이용해 재귀 함수와 같은 형식으로 만든 점은 창의적인 방법이라 칭찬하지만,
굳이 setInterval를 쓰지 않고 setTimeout을 사용해 로직을 볼 때 한번 더 생각하게 되는 코드를 작성한 것은 코드 가독성 측면에서는 불필요한 코드인 것 같습니다.
setTimeout을 쓰고자 하는 명확한 근거가 없다면 setInterval을 사용해 보다 가독성 있는 코드를 작성해주세요

2022-11-01 16:17 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +const $userTargets = [...document.querySelectorAll(".user img")];
document.querySelectorAll(".user img")의 반환 값은 이미 배열임에도 rest와 []을 같이 쓰지 않아도 배열로 할당됩니다.
다른 이유가 없는거라면, document.querySelectorAll(".user img")만 남겨주세요

2022-11-01 16:17 UTC, dokdogalmaegi commented on Task/first.js
> +  [...arguments].map(t => {
map 함수는 새로운 자료구조의 배열을 만들기 위해서 사용하는 함수입니다.
Ex) String Array -> Number Array, Object Array -> String Array

그러나 현재 사용하신 map은 새로운 자료구조의 배열을 위한이 아닌, forEach 형태의 로직을 구현하고 있는 것으로 보입니다.
map을 사용하는 방법이 익숙하지 않다면, 사용하지 않는 것으로 권장합니다.

코드에 있는 map을 forEach로 바꿔주세요

2022-11-01 16:17 UTC, dokdogalmaegi commented on Task/first.js
> +    const text1 = `* ${t} *`;
text1이라는 변수명 보다는 centerText 또는 mainText라는 이름과 같이 명확한 이름으로 명명 부탁드립니다.

2022-11-01 16:17 UTC, dokdogalmaegi commented on Task/first.js
> +    const text2 = arr.join("");
text2 보다 명확한 starBorder, border 과 같은 이름으로 명명 부탁드립니다.

2022-11-01 16:17 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +    $userTargets.map(t => {
first.js 내용과 같이 map은 새로운 자료구조 배열을 위한 함수입니다.
변경해주세요

2022-11-01 16:17 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +let eventTarget = null;
eventTarget이라는 변수명은 너무 추상적인 이릉입니다.
보다 명확하게 selected라는 이름 처럼 사용자가 선택했다. 라는 의미를 줄 수 있는 변수명으로 변경해주세요

2022-11-02 00:15 UTC, dokdogalmaegi requested changes

2022-11-02 00:15 UTC, dokdogalmaegi commented on Task/first.js
> +  [...arguments].map(t => {
arguments 말고 rest 문법을 사용해주세요

2022-11-02 08:19 UTC, youngjoon568 commented on Clock/Clock.js
> +const $ = e => document.querySelector(e);
알겠습니다 수정하도록 하겠습니다

2022-11-02 08:19 UTC, youngjoon568 commented on Clock/Clock.js
> +const textPad = str => String(str).padStart(2, "0");
textPad 함수를 없앴습니다.

2022-11-02 08:21 UTC, youngjoon568 commented on Clock/Clock.js
> +        if(text === "AM" && hours === 0) {
오전 12시를 표현하기 위함입니다.

2022-11-02 08:23 UTC, youngjoon568 commented on Clock/Clock.js
> +    setTimeout(() => {
setTimeout를 쓰려고 한 이유는 setInterval을 사용하면 setInterval(watch, 1000); 이런 식으로 사용하면 1초 뒤에 시간이 보여지기 때문입니다. 그래서 먼저 함수 실행하고 setTimeout로 1초 뒤에 다시 함수 실행하는 방식으로 반복하였습니다.

2022-11-02 08:40 UTC, youngjoon568 commented on Clock/Clock.js
> +const textPad = str => String(str).padStart(2, "0");
timePad로 수정하여 타입 체크를 하고 있습니다.

2022-11-02 08:41 UTC, youngjoon568 commented on Task/first.js
> +  [...arguments].map(t => {
rest 문법으로 변경하였습니다.

2022-11-02 10:25 UTC, dokdogalmaegi approved these changes
리뷰 끝입니다.

2022-11-02 10:26 UTC, fred16157 approved these changes
👍

2022-11-02 10:28 UTC, merged