과제 제출
team-jigun/JavaScript-Class pull request #19
Opened 2022-11-01 13:18 UTC by mingi502

과제 제출합니다.

2022-11-01 14:24 UTC, fred16157 reviewed
큰 문제는 없어보이네요.. 개선할 만한 곳에 코멘트를 달아두었습니다
PR이 머지될 base 브랜치를 main에서 자기 닉네임이 적힌 브랜치로 바꿔주시면 approve 드리겠습니다
참고: 오른쪽 위에 edit 버튼을 누르면 이런 화면이 나옵니다
![image](https://user-images.githubusercontent.com/25629441/199256302-491d0b0e-f2a4-4b0d-a9bf-14b72c36805e.png)

2022-11-01 14:24 UTC, fred16157 commented on RockScissorsPaper/RockScissorsPaper.js
> +    setTimeout(() => {
if 케이스들 공통적으로 clearInterval을 호출하고 있는데, 중간에 return 등 벗어나는 코드가 없으므로 이런 중복되는 코드는 if문을 벗어나고 나서 호출해도 늦지 않습니다.

여기 중괄호와 setTimeout 사이로 옮기고, 나머지는 지우셔도 잘 작동할 거에요

2022-11-01 16:49 UTC, dokdogalmaegi requested changes
getTime 함수 분리

2022-11-01 16:49 UTC, dokdogalmaegi commented on Clock/Clock.js
> +function getTime(){
getTime이라는 이름을 가지고 있지만,
실제로 하는 역할은 clock Element의 텍스트 값까지 바꾸고 있습니다.
함수 이름과 실제 하는 수행 로직 차이점이 존재합니다.

텍스트를 바꾸는 Action, 현재 시간을 받아오는 Action 2개를 분리하여 함수를 작성해주세요

2022-11-02 00:16 UTC, dokdogalmaegi requested changes

2022-11-02 00:16 UTC, dokdogalmaegi commented on Task/first.js
> +  for(let i of arguments) {
arguments 말고 rest 문법을 사용해주세요

2022-11-02 10:57 UTC, dokdogalmaegi requested changes
리뷰 반영 해주세요

2022-11-02 10:57 UTC, dokdogalmaegi commented on Clock/Clock.js
> +function set(){
불필요 함수입니다.
삭제 부탁드립니다.

2022-11-03 13:45 UTC, mingi502 commented on Clock/Clock.js
> +function set(){
삭제 했습니다.

2022-11-03 13:46 UTC, mingi502 commented on Clock/Clock.js
> +function set(){
수정했습니다.

2022-11-03 13:46 UTC, mingi502 commented on Task/first.js
> +  for(let i of arguments) {
수정했습니다.

2022-11-04 11:59 UTC, dokdogalmaegi requested changes
변수명만 수정해주세요

2022-11-04 11:59 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +let Result = document.querySelector(".body");
변수명이 굉장히 추상적인 것 같습니다.
camelCase를 지켜주시면서, resultElement 또는 resultElem 등으로 변경하는 건 어떨까요?

변수명만 변경해주시면, Approved 해드리겠습니다.

2022-11-04 13:45 UTC, mingi502 commented on RockScissorsPaper/RockScissorsPaper.js
> +let Result = document.querySelector(".body");
수정했습니다.

2022-11-06 04:30 UTC, dokdogalmaegi approved these changes
리뷰 완료하였습니다.

2022-11-07 13:17 UTC, merged