4일차 과제 제출
team-jigun/JavaScript-Class pull request #21
Opened 2022-11-01 14:44 UTC by Happi3r

2022-11-01 16:41 UTC, dokdogalmaegi requested changes

2022-11-01 16:41 UTC, dokdogalmaegi commented on Clock/Clock.js
> +    const h = String(now.getHours()).padStart(2, '0');
실제로 출력되는 값은 hh이기 때문에 m, s 도 동일하게
hh, mm, ss 와 같은 변수명이나 hours, minutes, seconds와 같이 보다 명확한 변수명이 좋을 것 같습니다.

2022-11-01 16:41 UTC, dokdogalmaegi commented on Task/first.js
> +  const max = Math.max(...[...arguments].map(v => String(v).length));
arguments는 rest 문법으로 수정해주세요
arguments는 사용을 권장하지 않습니다.

2022-11-01 16:41 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +    document.querySelector('.dropzone').addEventListener('dragleave', () => {
로직은 창의성은 10점 만점의 10점이지만,
읽었을 때 바로 이해하지 못하기 때문에 가독성이 매우 떨어지기 때문에, 좋은 코드라고 보기에는 많이 부족합니다.
가위바위보 코드는 수정은 선택으로 남기겠습니다.

2022-11-02 00:46 UTC, Happi3r commented
수정사항 업데이트 했습니다.

2022-11-02 09:39 UTC, Happi3r commented
확인 부탁드립니다

2022-11-03 12:25 UTC, dokdogalmaegi approved these changes
확인했습니다.

2022-11-03 12:25 UTC, merged