김준철
team-jigun/JavaScript-Class pull request #23
Opened 2022-11-01 15:53 UTC by jammykii

과제제출입니다

2022-11-02 00:17 UTC, dokdogalmaegi requested changes

2022-11-02 00:17 UTC, dokdogalmaegi commented on Clock/Clock.js
> +function Time() {
불필요 함수입니다.

따로 이유가 없다면 지워주세요

2022-11-02 00:17 UTC, dokdogalmaegi commented on Task/first.js
> +  for (let i of arguments) {
arguments 말고 rest 문법을 사용해주세요

2022-11-02 11:09 UTC, jammykii commented
수정했습니다

2022-11-03 12:33 UTC, dokdogalmaegi approved these changes
리뷰는 마무리 되었으나, 본인이 원하시면 리뷰 내용 읽으시고 코드 수정 해보는 것도 좋을 것 같습니다.
(수정은 강요가 아니라 권유이며, 하지 않고 바로 Merge 누르셔도 됩니다)

2022-11-03 12:33 UTC, dokdogalmaegi commented on Task/first.js
> +  let result = max(arguments) + 2;
arguments가 남아있지만, 수정은 선택으로 남겨 놓겠습니다.

2022-11-03 12:33 UTC, dokdogalmaegi commented on Clock/Clock.js
> +function getTime() {
getTime 함수에서 작동하는 로직이 총 2가지이며, 함수 이름과 맞지 않습니다.
Time을 받는 함수인 것 같지만, 실제로 동작하는 로직은 시간을 받아오는 것이 화면에 시간을 바꾸는 역할을 하고 있습니다.
이 때는 getTime 보다는 changeClockTime 등 동작 로직과 동일하게 이름을 명명하거나, 함수를 2개로 나누어 getTime, changeTime 로직을 분리하는 것이 더 좋습니다.
일단 위 리뷰 내용은 선택으로 남겨 놓도록 하겠습니다.
수고 많으셨습니다.

2022-11-07 04:20 UTC, merged