이상혁 - 숙제 제출
team-jigun/JavaScript-Class pull request #24
Opened 2022-11-02 09:13 UTC by Capella42

[제출합니다]

2022-11-02 10:49 UTC, dokdogalmaegi requested changes
1차 리뷰, 수정 후 다시 리뷰 요청해주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on Clock/Clock.html
> +<script src="./Clock.js"></script>
js 파일을 head 쪽으로 옮겨주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on Clock/Clock.js
> +    console.log(day);
디버깅 코드 없애주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on Clock/Clock.js
> +    let day = new Date();
변수 값 변경이 없을 때는 const 예약어를 사용해 변수를 선언해주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +function rsp(){
함수 선언이 호출 구문보다 위에 있도록 해주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on RockScissorsPaper/RockScissorsPaper.js
> +    console.log(e)
디버깅 코드 없애주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on Task/first.js
> +  Asterisk = "**";
변수 선언과 변수 명을 asterisk(camelCase)로 변경해주세요

2022-11-02 10:49 UTC, dokdogalmaegi commented on Task/first.js
> +  for (let i of arguments) {
arguments 말고 rest 문법을 사용해주세요
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/rest_parameters

2022-11-02 12:11 UTC, Capella42 commented on Clock/Clock.html
> +<script src="./Clock.js"></script>
수정했습니다

2022-11-02 12:11 UTC, Capella42 commented on Clock/Clock.js
> +    console.log(day);
수정했습니다

2022-11-02 12:11 UTC, Capella42 commented on Clock/Clock.js
> +    let day = new Date();
수정했습니다

2022-11-02 12:11 UTC, Capella42 commented on RockScissorsPaper/RockScissorsPaper.js
> +function rsp(){
수정했습니다

2022-11-02 12:11 UTC, Capella42 commented on RockScissorsPaper/RockScissorsPaper.js
> +    console.log(e)
수정했습니다

2022-11-02 12:11 UTC, Capella42 commented on Task/first.js
> +  for (let i of arguments) {
수정했습니다

2022-11-03 12:42 UTC, dokdogalmaegi approved these changes
확인했습니다.

2022-11-04 08:47 UTC, merged