Express과제 제출
team-jigun/JavaScript-Class pull request #31
Opened 2022-11-06 10:20 UTC by mingi502

과제 제출

2022-11-06 23:31 UTC, dokdogalmaegi requested changes
전에 리뷰 완료된 과제 먼저 머지 해주시고, 다시 리뷰 요청을 만들어주세요
파일이 충돌나고 있습니다.

2022-11-07 10:44 UTC, mingi502 reviewed
5일차 과제 재제출

2022-11-07 13:07 UTC, dokdogalmaegi requested changes
이때까지 한 과제를 삭제하지 마시고, 이전에 요청하신 Merge Request를 Merge를 하세요

2022-11-08 14:37 UTC, dokdogalmaegi requested changes
실수로 파일을 이미 올리셔서 해당 리뷰 closed 하겠습니다.

2022-11-08 14:37 UTC, closed without merging