5일차 과제
team-jigun/JavaScript-Class pull request #32
Opened 2022-11-06 23:17 UTC by youngjoon568

제출 완료

2022-11-07 13:41 UTC, fred16157 requested changes

2022-11-07 13:41 UTC, fred16157 commented on ExpressStudy/index.js
> +        addupNum = parseInt(arr[i] === arr[0] ? 0 : arr[i]);
삼항연산자에 오류가 있는 것 같군요.
어떤 오류인지는 1을 4번 더해보시면 알게 될겁니다.

값이 아니라 인덱스끼리 비교하시거나 아예 i를 1부터 시작하게 만들어야 하지 않을까 싶습니다.

2022-11-07 13:41 UTC, fred16157 commented on ExpressStudy/index.js
> +        num = parseInt(arr[i] === arr[0] ? 0 : arr[i]);
여기도 마찬가지로 삼항연산자에 오류가 있습니다.

2022-11-07 13:41 UTC, fred16157 commented on ExpressStudy/index.js
> +    };
음 nums에 이미 배열로 들어올텐데 다시 arr에 넣으시는 이유가 궁금합니다

2022-11-07 13:41 UTC, fred16157 commented on ExpressStudy/index.js
> +    let num = 0;
여기서 num을 정의하지 않고, 아래에서 for문 안에 parseInt 결과를 받아서 const로 할당할 수 있습니다.

2022-11-07 13:53 UTC, dokdogalmaegi requested changes
1차 리뷰 완료, 수정 부탁드립니다.

2022-11-07 13:53 UTC, dokdogalmaegi commented on ExpressStudy/index.js
> +    const plusQuery = req.query.num;
밑에서는 변수명을 nums로 사용하였는데, 여기서는 plusQuery라고 사용한 이유가 있을까요? 

동일한 의미를 가지고 있는 변수임에도 변수명이 다른 건 별로 좋은 방향은 아닌 것 같습니다.

2022-11-07 13:53 UTC, dokdogalmaegi commented on ExpressStudy/index.js
> +    const arr = [];
필요 없는 배열입니다.
해당 배열을 사용하지 않는 방향으로 수정 검토 부탁드립니다.

2022-11-07 13:53 UTC, dokdogalmaegi commented on ExpressStudy/index.js
> +    let addupNum = 0;
필요 없는 변수입니다.
해당 변수를 사용하지 않는 방향으로 수정 검토 부탁드립니다.
만약, 사용한 의도가 있다면 그 의도를 말씀해주세요

2022-11-07 13:53 UTC, dokdogalmaegi commented on ExpressStudy/index.js
> +    const type = req.query.type;
타입을 받았을 때 타입 체크를 하는 것이
아래 로직을 동작하지 않기 때문에 보다 효율적이고, 가독성 좋은 코드를 만들 수 있습니다.
로직을 모두 돌린 뒤 타입체크를 하는 것은 의미가 없는 타입 체크입니다.

2022-11-07 13:53 UTC, dokdogalmaegi commented on ExpressStudy/index.js
> +            case SIGN_TYPE.PLUS:  target += num; break;
무조건 코드가 짧다고 해서 가독성이 늘어나는 코드는 아닙니다.
아무리 간단한 로직이라고 하더라도, 한눈에 보이는 것과 한줄에 보이는 건 다른 겁니다.
한줄 작성이 아닌 평소와 같이 switch case를 사용해주세요

2022-11-07 13:53 UTC, dokdogalmaegi commented on ExpressStudy/index.js
> +            default: throw Error("타입이 존재하지 않습니다.");
서버에서 아무런 처리 없이, Error를 Throw하는 건 책임 없는 Throw입니다.
에러가 발생한다면, 에러 페이지를 return하고 에러 문구를 log로 출력한다던가
그것이 아니라면, 적어도 에러 페이지에 대한 내용을 담은 send를 주어야 합니다.
무책임한 Throw는 없애주세요.

2022-11-07 13:57 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    };
수정하겠습니다.

2022-11-07 14:18 UTC, youngjoon568 commented on ExpressStudy/index.js
> +            case SIGN_TYPE.PLUS:  target += num; break;
switch case문은 원래 이렇게 사용해 왔습니다. 수정하도록 하겠습니다.

2022-11-07 14:19 UTC, youngjoon568 commented on ExpressStudy/index.js
> +            default: throw Error("타입이 존재하지 않습니다.");
Throw를 없애고 addedNum을 반환하게 했습니다.

2022-11-07 14:21 UTC, youngjoon568 commented on ExpressStudy/index.js
> +        addupNum = parseInt(arr[i] === arr[0] ? 0 : arr[i]);
i를 1부터 시작하고 인덱스끼리 비교하도록 수정하였습니다.

2022-11-07 14:22 UTC, youngjoon568 commented on ExpressStudy/index.js
> +        num = parseInt(arr[i] === arr[0] ? 0 : arr[i]);
수정하였습니다.

2022-11-07 14:22 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    let num = 0;
수정하였습니다.

2022-11-07 14:23 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    const plusQuery = req.query.num;
plusQuery plus만 받는 쿼리여서 변수명을 저렇게 하였는데 수정하였습니다.

2022-11-07 14:23 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    const arr = [];
필요 없는 배열을 삭제하였습니다.

2022-11-07 14:23 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    let addupNum = 0;
필요 없는 변수를 삭제하였습니다.

2022-11-07 14:24 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    const type = req.query.type;
선언 후 if문으로 체크하여 아래 로직을 동작하지 않게 하였습니다.

2022-11-07 14:38 UTC, youngjoon568 commented on ExpressStudy/index.js
> +            default: throw Error("타입이 존재하지 않습니다.");
addedNum만 디폴트에 넘겨 주었고 에러 처리를 선언하자 마자 했습니다.

2022-11-08 08:05 UTC, fred16157 requested changes
(선택) 커밋 기록을 보니 node_modules 안에 있던 것들이 커밋으로 올라와서 놀라셨을텐데, 이런 git에 올릴 필요없는 파일은 .gitignore 파일을 활용하여 관리하시면 삶의 질이 높아집니다.

2022-11-08 08:05 UTC, fred16157 commented on ExpressStudy/index.js
> +    if((!numQuery || !type) || (type !== SIGN_TYPE.PLUS && type !== SIGN_TYPE.MINUS && type !== SIGN_TYPE.MULTIPLY && type !== SIGN_TYPE.DIVISION)) {
type이 지정하신 SIGN_TYPE 내에 없는지 체크하고 싶으신거면, Object.values(SIGN_TYPE).contains(type) 같은 방법으로 간소화가 가능하고 추후 수정이 필요할 때도 할일이 줄어듭니다.

2022-11-08 08:05 UTC, fred16157 commented on ExpressStudy/index.js
> +        const addupNum = parseInt(i === numQuery ? 0 : numQuery[i]);
i가 1부터 시작한다면 삼항연산자를 쓸 필요 없이 numQuery[i]만 남기면 되지 않나요?

2022-11-08 08:05 UTC, fred16157 commented on ExpressStudy/index.js
> +        const addupNum = parseInt(i === numQuery ? 0 : numQuery[i]);
> i가 1부터 시작한다면 삼항연산자를 쓸 필요 없이 numQuery[i]만 남기면 되지 않나요?

여기도 마찬가지

2022-11-08 08:08 UTC, fred16157 commented on ExpressStudy/index.js
> +        const addupNum = parseInt(i === numQuery ? 0 : numQuery[i]);
그리고.. numQuery는 배열이고 i는 인덱스(number)라서 타입이 다르기 때문에 === 비교가 항상 false로 나옵니다.

2022-11-08 08:25 UTC, youngjoon568 commented on ExpressStudy/index.js
> +        const addupNum = parseInt(i === numQuery ? 0 : numQuery[i]);
0이랑 같다는 걸 비교 했어야 됐는데 햇갈렸습니다. 필요 없는 삼항 연산자를 삭제하여 수정하도록 하겠습니다.

2022-11-08 12:00 UTC, youngjoon568 commented on ExpressStudy/index.js
> +        const addupNum = parseInt(i === numQuery ? 0 : numQuery[i]);
수정하였습니다.

2022-11-08 12:00 UTC, youngjoon568 commented on ExpressStudy/index.js
> +    if((!numQuery || !type) || (type !== SIGN_TYPE.PLUS && type !== SIGN_TYPE.MINUS && type !== SIGN_TYPE.MULTIPLY && type !== SIGN_TYPE.DIVISION)) {
수정하였습니다.

2022-11-08 14:14 UTC, fred16157 approved these changes
준영이 승인도 받으시면 머지해주세요

2022-11-08 14:15 UTC, youngjoon568 commented
알겠습니다!

2022-11-08 14:21 UTC, dokdogalmaegi approved these changes
리뷰 완료하였습니다.
추가 피드백은 수업 시간에 같이 보도록 하겠습니다.

2022-11-08 14:42 UTC, merged