Revert "10.26 수업과제"
team-jigun/JavaScript-Class pull request #37
Opened 2022-11-08 23:06 UTC by yvsc5020

Reverts team-jigun/JavaScript-Class#15

2022-11-08 23:07 UTC, yvsc5020 commented
죄송합니다, 머지하다가 실수로 express강의 과제도 같이 머지해버렸는데 머지 풀어주실 수 있나요?

2022-11-09 01:22 UTC, dokdogalmaegi commented
>

2022-11-09 01:23 UTC, dokdogalmaegi requested changes
일단 해당 PR은 Close 하였습니다.

나중에 과제만 추가하시고, 다시 PR 주세요

2022-11-09 01:27 UTC, dokdogalmaegi commented
> 죄송합니다, 머지하다가 실수로 express강의 과제도 같이 머지해버렸는데 머지 풀어주실 수 있나요?

해당 PR을 close 요청주신게 맞죠?
아니라면, 따로 연락 부탁드립니다.

2022-11-09 01:27 UTC, closed without merging

2022-11-09 01:31 UTC, dokdogalmaegi commented
아 지금 다시 보니 이전 과제 올리시면서 같이 Express도 올리셔서 그런거죠?
그럼 제가 node_modules 폴더만 따로 삭제 작업을 하고, 코드 리뷰는 오늘 수업시간에 진행하는것으로 하겠습니다.
나중에 수업시간에 봐요